html/kumeta/library/book.html

ISBN値のミス修正

---

public/assets/script/_src/unique/SidebarBlogNewly.ts
public/assets/style/_src/object/project/_sidebar.css

日記新着 JSON ファイルのタイトルが text 型から HTML 型に変更されることに伴う改修

---

public/assets/script/_src/error.ts

`error.ts` の全体的な調整

---

html/kumeta/index.html
html/kumeta/library/book.html

「spoon.2Di Vol.24」「spoon.2Di Vol.26」のデータ、および「季刊エス 32号」の色紙情報を追加。

「メディア紹介 — 図書、一般雑誌」に情報追加

---

public/assets/style/_src/layout/_common.css
public/assets/style/_src/object/project/_footer.css
public/assets/style/_src/object/project/_main-form.css
public/assets/style/_src/object/project/_main-tokyu-set.css
public/assets/style/_src/object/project/_main-top.css

Container Queries 導入

---

.stylelintrc.json
public/assets/style/_src/layout/_common.css
public/assets/style/_src/object/project/_main-top.css

Container Queries 関連のプロパティオーダーの設定を追加

---

node/src/build/HtmlImageSize.ts
node/src/controller/api/AmazonAdsJsonController.ts
node/src/dao/AmazonAdsDao.ts

`for...of` ループを `await Promise.all([...XXX].map(async () => { ... }))` に置き換える

ESLint の `no-await-in-loop` エラーを解消

---

.markuplintrc
errorpage/403.html
errorpage/404.html
package-lock.json
package.json
views/_include/_header.ejs
views/_include/_header_kumeta.ejs
views/_include/_header_madoka.ejs
views/_include/_header_tokyu.ejs

サイト内検索に `<search>` 要素を使用する

---

.markuplintrc
package-lock.json
package.json

Markuplint 3.6 にアップデート、エラー回避の暫定的な設定変更を復帰

---

.eslintrc.json
package-lock.json
package.json
public/assets/script/_src/trusted-types.ts
rollup.config.js

- JS ファイルに `use strict` を追加
- ただし `analytics.ts` は対象外とする

モジュールではない JS ファイルを strict モードにする

---

html/privacy.html
html/privacy.json

以前書いたつもりだったが、抜けていたので追加した。
その他の節も文面を見直している。
いずれも、挙動そのものは以前から変わっていない。

プライバシーポリシーに YouTube 埋め込み動画について追加

---

html/kumeta/manga/list.html
html/tokyu/sty/aps.html

- 見出しレベル（hn の数字）ミス
- section の挿入位置ミス

見出し関係の HTML バグ修正

---

html/privacy.html
html/privacy.json

- SaekiTominaga/blog.w0s.jp/pull/296 にてツイート埋め込みを廃止したため、それに関する記述を削除
- その他の項目も内容自体は大きく変わらないものの、文面の変更やリンク先 URL の変更に追従するなど全面的に見直し

プライバシーポリシー改訂

---

astro/src/components/LibraryItemNewspaper.astro
astro/src/pages/kumeta/library/newspaper.astro
astro/src/pages/madoka/library/newspaper.astro

HTML と class 属性と判定され、エディター上で Markuplint 警告が出る

Astro コンポーネントの `class` 属性名を変える

---

package-lock.json
package.json

`onchange` はもう使っていないので削除

---

astro/src/components/LinkExternal.astro
astro/src/layouts/include/ContentFooter.astro
astro/src/pages/500.astro
astro/src/pages/info.astro
astro/src/pages/kumeta/kumeta/interview.astro
astro/src/pages/kumeta/library/book.astro
astro/src/pages/kumeta/library/newspaper.astro
astro/src/pages/kumeta/manga/color.astro
astro/src/pages/kumeta/manga/list.astro
astro/src/pages/kumeta/manga/subtitle.astro
astro/src/pages/kumeta/yomoyama/kuigaten.astro
astro/src/pages/kumeta/yomoyama/zetsubou_web.astro
astro/src/pages/madoka/dojin/pictorial10.astro
astro/src/pages/madoka/dojin/pictorial11.astro
astro/src/pages/madoka/dojin/pictorial7.astro
astro/src/pages/madoka/dojin/pictorial9.astro
astro/src/pages/madoka/dojin/zaiko.astro
astro/src/pages/madoka/event/1kuji.astro
astro/src/pages/madoka/event/event.astro
astro/src/pages/madoka/event/genga.astro
astro/src/pages/madoka/event/madogatari.astro
astro/src/pages/madoka/event/shaft.astro
astro/src/pages/madoka/event/shop.astro
astro/src/pages/madoka/event/umeten.astro
astro/src/pages/madoka/yomoyama/official_news.astro
astro/src/pages/tokyu/book/7700.astro
astro/src/pages/tokyu/data/preservation.astro
astro/src/pages/tokyu/yomoyama/ibaraki_6000.astro

- 外部サイトへのリンクに `rel=external` を設定
- ドメイン・アイコンを表示しない外部リンクも `<LinkExternal>` に置き換える

外部サイトへのリンクに `rel=external` を設定

---

astro/style/layout/_common.css
astro/style/layout/_error.css
astro/style/object/component/_form.css
astro/style/object/component/_layout.css
astro/style/object/component/_text.css
astro/style/object/component/_tokyu.css
astro/style/object/project/_content.css
astro/style/object/project/_error.css
astro/style/object/project/_footer.css
astro/style/object/project/_header.css
astro/style/object/project/_main-embedded.css
astro/style/object/project/_main-form.css
astro/style/object/project/_main-kumeta-twitter.css
astro/style/object/project/_main-library.css
astro/style/object/project/_main-link.css
astro/style/object/project/_main-list.css
astro/style/object/project/_main-section.css
astro/style/object/project/_main-tokyu-announce.css
astro/style/object/project/_main-tokyu-data.css
astro/style/object/project/_main-tokyu-set.css
astro/style/object/project/_main-tokyu.css
astro/style/object/project/_main-top.css
astro/style/object/project/_main.css
astro/style/object/project/_sidebar.css
astro/style/object/utility/_kumeta.css

`display` プロパティの値を2値構文に変更

---

astro/src/pages/kumeta/kumeta/interview.astro
astro/src/pages/kumeta/library/book.astro
astro/src/pages/madoka/library/book.astro
astro/src/pages/madoka/library/magazine.astro

雑誌「月刊ニュータイプ」は「ニュータイプ」でなく「月刊ニュータイプ」が正式名称

---

astro/package.json
astro/rollup.config.js
astro/script/error.ts
package-lock.json
package.json

npm パッケージの Organization 変更に伴う修正（`closest-html-page`）

---

astro/src/layouts/include/ContentFooter.astro

問い合わせコンポーネントの開閉アニメーションが効いていなかったバグを修正

---

.github/workflows/astro@css-lint.yml
.github/workflows/astro@html-lint.yml
.github/workflows/astro@js-lint.yml
.github/workflows/astro@lint.yml
.github/workflows/astro@node-lint.yml
.github/workflows/express@lint.yml
.github/workflows/github-actions-lint.yml

Node.js バージョン 20 にアップデート

---

astro/src/+type/types.ts
astro/src/+util/StructuredData.ts
astro/src/pages/info.astro

プロフィールページの JSON-LD に `mainEntry` プロパティを追加

---

astro/src/pages/kumeta/library/web.astro
astro/src/pages/kumeta/manga/color.astro

表のマークアップミス（修正漏れ）によりスタイルが適用されていなかったバグを修正

---

astro/src/pages/tokyu/data/history_mekama&toyoko_passenger.astro
astro/src/pages/tokyu/data/index.astro

#484 の誤記や対応漏れ
- index ページの更新日変更忘れ
- 認可番号ミス修正

車両履歴の誤記修正など

---

astro/src/pages/index.astro
astro/src/pages/info.astro

- 興味の詳細文を追加
- Mastodon と Bluesky の使い分けを明記
- まどか資料館へのリンクを外す

制作者ページを全面的に改修

---

astro/src/pages/technology.astro

前回更新から Astro 導入などかなり環境が変わっているので全面的に見直した。

「当サイトの Web 技術」を更新

---

astro/.postcssrc
astro/package.json
package-lock.json

`postcss-media-minmax` 除去

---

astro/src/pages/technology.astro

「当サイトの Web 技術」の invalid な HTML を修正

---

astro/style/object/project/_main-section.css

見出しのセルフリンクのスタイルを微調整

---

astro/script/error.ts

エラーページが `<portal>` 要素で表示される可能性を考慮した処理の削除

---

astro/src/layouts/include/PageHeader.astro
astro/src/layouts/include/PageHeaderKumeta.astro
astro/src/layouts/include/PageHeaderMadoka.astro
astro/src/layouts/include/PageHeaderSearch.astro
astro/src/layouts/include/PageHeaderTokyu.astro
astro/style/layout/_common.css
astro/style/object/project/_header.css

- `.p-header-site` 内を常に縦並びにするほかは見た目の変更なし
- 主にクラス名や CSS の見直し

ページヘッダーのスタイル修正

---

astro/style/foundation/_var.css

フォームの invalid 時に入力欄の赤色枠線が表示されていないバグを修正

---

astro/src/pages/tokyu/data/index.astro
astro/src/pages/tokyu/index.astro

#558 の作業ミス修正

---

astro/package.json
package-lock.json

脚注ポッポオーバー内のテキストが閉じるボタンと重なる事象が発生したため

PostCSS Nesting@12 に戻す

---

astro/src/pages/tokyu/data/history_mekama&toyoko_passenger.astro

譲渡届出制に関する参考文献を変更

---

astro/src/pages/tokyu/data/history_ikegami.astro

リンクのコピペミスを修正

---

astro/script/error.ts
astro/script/w0s.ts

report.w0s.jp のエンドポイント URL を変更（対応漏れ）

---

.gitignore
astro/src/+util/ssr.ts
express/src/app.ts

#607 のバグ修正
Astro の SSR ページが正常に表示されなかったので env ファイルと log4js 設定ファイルの配置場所を変更

env ファイルと log4js 設定ファイルの配置場所を変更

---

.github/workflows/astro@node.yml

ビルド処理の TypeScript 化に伴う修正漏れ

---

frontend/script/unique/SidebarBlogNewly.ts

サイドバーのブログ記事 URL 変更

---

frontend/package.json
frontend/rollup.config.js
package-lock.json

- `terser` による minify 処理の廃止
- ソースマップのバンドルファイル内コメントを廃止
- その他設定を全面的に精査

Rollup 設定変更

---

astro/src/pages/admin/crawler-news/data.astro
astro/src/pages/admin/crawler-news/index.astro
astro/src/pages/admin/crawler-resource/diff.astro
astro/src/pages/admin/crawler-resource/index.astro
astro/src/pages/admin/crawler-resource/log.astro
astro/src/pages/contact.astro
astro/src/pages/tokyu/data/history/index.astro

`env()` を npm に差し替え（Astro pages）

---

astro/package.json
astro/src/+dao/CrawlerDao.ts
astro/src/+dao/CrawlerNewsDao.ts
astro/src/+dao/CrawlerNewsDataDao.ts
astro/src/+dao/CrawlerResourceDao.ts
astro/src/+dao/TokyuCarHistoryDao.ts
astro/src/+util/db.ts
astro/src/+util/request.ts
astro/src/pages/admin/crawler-news/data.astro
astro/src/pages/admin/crawler-news/index.astro
astro/src/pages/admin/crawler-resource/diff.astro
astro/src/pages/admin/crawler-resource/index.astro
astro/src/pages/admin/crawler-resource/log.astro
astro/src/pages/tokyu/data/history/index.astro
package-lock.json

合わせて以下の変更を実施
- null → undefined
- 入力欄に何も入力しなかったとき（リクエストで空文字が飛んでくる）を undefined 扱いにする処理を dao からリクエスト取得時に変更

`@w0s/sqlite-utility` 導入
