html/kumeta/library/newspaper.html
[さ さんのツイート](https://twitter.com/ni_saba/status/244813010101755904)より
> 今日の新聞に載ってた絶望先生カフカの話。とてもよかった。泣いてしまった。
現紙を確認したが、読売新聞1面に掲載されていたフランツ・カフカのコラムのことと思われ、『さよなら絶望先生』とは無関係だった。
=> 2012年9月9日の新聞記事は絶望先生と無関係だったので削除

html/kumeta/index.html, html/kumeta/library/manga.html
- 週刊少年サンデー 2018年18号のデータ追加
- 週刊少年サンデー 2022年44号のページ数を電子版から紙版準拠に変更
=> 「メディア紹介 — 漫画雑誌」にデータ追加

public/assets/style/_src/object/project/_main-top.css
以前は一部ブラウザで上手くいかなかったので、子孫要素にも `border-radius` を掛ける方法でやっていたが、 Firefox, Chrome, Safari の最新版で問題ないようだったので `overflow: hidden` に変更する
=> `border-radius` を掛けている子孫要素に `background` がある場合に背景がはみ出るのを `overflow: hidden` で解決するように変更

views/xml/sitemap.ejs
=> まどか公式サイトニュースページの静的ページ化に伴い、サイトマップURL直書きから削除

html/madoka/index.html, html/madoka/library/book.html, html/madoka/library/magazine.html, html/madoka/library/newspaper.html
ほか、以下の変更を実施
- `<title>`, `<h1>` のテキストを見直し
- 更新日データがなかったので、それぞれ最後のデータの発売日を設定
=> まどかメディア紹介のデータを日付降順から昇順に変更

.markuplintrc, package-lock.json, package.json
- `embed`, `noscript` 要素の禁止設定を `@w0s/markuplint-config` に移行
- 一部ルールの無効化を `overrides` を使用して HTML ファイルには適用しない（EJS ファイルのみ除外させる）ように
=> `.markuplintrc` の見直し

.prettierrc, node/__tests__/util/PrettierUtil.test.js, node/src/build/Css.ts, node/src/build/Html.ts, node/src/util/PrettierUtil.ts
- 構成ファイルの読み込みと解析をメソッド分離
- `parser` オプションの強制指定をやめてあくまで構成ファイルに指定するように変更
=> PrettierUtil の更新

views/_include/head.ejs, views/_include/head_admin.ejs, views/_include/head_kumeta.ejs, views/_include/head_madoka.ejs, views/_include/head_tokyu.ejs
`defer` 属性や `async` 属性のファイル読み込み順序はブラウザによって異なるが、すべて `defer` に統一した場合は Firefox, Chrome ともソース順に読み込まれる。
=> `<script>` 要素による外部ファイル読み込みを `defer` に統一

html/kumeta/index.ejs, html/kumeta/library/manga.ejs
漫画雑誌の表紙情報はこれまで単独表紙ないし大きく掲載された事例のみとしていたが、小さな掲載例も含めてすべての事例を掲載するようにした
=> 漫画雑誌の表紙情報を小さな掲載例も含めて全事例を追加

.markuplintrc
これまで比較的サイズの大きいファイルはエラーが発生して lint 処理ができなかったため、`excludeFiles` で除外設定をしていたが、いつの間にか解消されていたので除外を止める。
=> Markuplint の `excludeFiles` から巨大 HTML ファイルを削除

views/tokyu-car-history.ejs
バージョン 2 でとうに廃止されていた。残っていることに悪影響はないが、不要なので削除する。
=> `@saekitominaga/customelements-input-switch` の `polyfill` 属性を削除

views/_include/head.ejs, views/_include/head_kumeta.ejs, views/_include/head_madoka.ejs, views/_include/head_tokyu.ejs
#289 で `<script>` 要素による外部ファイル読み込みを `defer` に統一したが、アクセス解析用途の 'matomo.js' は `async` でしか動かないため元に戻す
=> 'matomo.js'  の読み込みタグを async に戻す

node/tsconfig.json, package-lock.json, package.json
TypeScript 設定の [`moduleResolution`](https://www.typescriptlang.org/tsconfig#moduleResolution) を `Node16` に上げられる。
👉https://github.com/highlightjs/highlight.js/issues/3481
=> highlight.js 11.8 にアップデート

html/kumeta/library/manga.html
> このカッコいい伯爵のイラストは、マガジンの全キャラ集合表紙用に描かれたもので、完成した表紙では他のキャラに紛れて、顔と帽子しか見えてなかったという憂き目に遭ったものなのです。日の目を見させてあげられて良かったです。
[くめたん（久米田康治先生担当編集ズ）さんはTwitterを使っています](https://twitter.com/kume_tantou/status/746346944994304001)
=> 週刊少年マガジン 2014年1号の表紙イラスト補足を追加

packages/backend/node/src/controller/CrawlerResourceLogController.ts
ログファイル格納ディレクトリが存在しないとき、画面上は件数0件時と区別が付かず、エラーログへの過去込みも行われていなかったため原因特定が困難であった。
=> ログファイル格納ディレクトリの存在チェックを追加

packages/frontend/node/src/build/Html.ts
#307 の変更で HTML ビルドプログラムに渡す引数のパスが変わったために発生したバグ
=> GitHub ソースコードの URL が正しくないバグを修正

html/admin/crawler-resource.ejs, packages/backend/node/@types/view.d.ts, packages/backend/node/src/controller/CrawlerResourceController.ts, packages/backend/node/src/dao/CrawlerResourceDao.ts
SaekiTominaga/w0s.jp-shell/pull/48 に伴う修正
- 「ハッシュ値」列を追加
- 「サイズ」「更新日時」列を廃止
- 「エラー」列追加
=> 「ウェブ巡回（リソース）」の差分比較をコンテンツの長さ→ハッシュ値に変更

.github/workflows/astro@html-lint.yml, .github/workflows/astro@lint.yml
[GitHub Actions のワークフロー構文 - GitHub Docs](https://docs.github.com/ja/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet)によると、`paths` の glob パターンに `*.{html, htm}` のような { } を使った複数の拡張子パターンは指定できないようだ。
=> GitHub Actions の `paths` で一行内に複数の拡張子は指定不可

astro/package.json
本番サーバーで `astro check` や `astro build` を行うと `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` が発生する。
そのため、開発環境で実施済み（のはず）の `astro check` は省略し、また `astro build` の実行に際しては `--max-old-space-size` オプションを指定する。
=> 本番サーバーでのビルド時のメモリ対策

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/book.astro, astro/src/pages/kumeta/library/manga.astro, astro/src/pages/kumeta/library/newspaper.astro, astro/src/pages/kumeta/manga/list.astro
- [作品リスト](https://w0s.jp/kumeta/manga/list)のページに『せっかち伯爵と時間どろぼう』の4コマ漫画2作を追加。
- [メディア紹介 — 漫画雑誌](https://w0s.jp/kumeta/library/manga)のページに「マガジン SPECIAL 2014年1号」、「マガジン SPECIAL 2014年2号」「マガジン SPECIAL 2014年8号」「楽園 Le Paradis 16号」を追加。
- [メディア紹介 — 図書、一般雑誌](https://w0s.jp/kumeta/library/book)のページに「声優グランプリ 2009年11月号」、「アニサマ公式メモリアル」（2010年）、「戦国大戦　攻略虎の巻」（2011年）、「戦国大戦 —1560 尾張の風雲児— 天下布武への道　〜攻略絵巻　春の陣〜」（2011年）を追加。
- [メディア紹介 — 新聞](https://w0s.jp/kumeta/library/newspaper)のページに「東京中日スポーツ 2021年7月12日」を追加。
=> 作品リスト、メディア紹介に情報追記

astro/script/component/TableTheadStickey.ts
#128 で対応を行ったが、#181 の改修で CS 変数名を変えたのに対して JS 側の変更漏れがあり、以来動いていなかった。
=> 脚注などから `.p-table` 内へのページ内アンカーで移動した際のスクロール位置調整機能が動いていない

astro/package.json, astro/template/xml/sitemap.ejs
- 4xx, 5xx 系のエラーページは sitemap.xml に載せない
- 赤松健セリフジェネレーターは廃止済みのためサイトマップからも削除（削除忘れ）
=> サイトマップに載せるべきでないコンテンツの除外設定

astro/style/object/component/_embedded.css
通常のテキスト（フォントサイズ 16px）内のアイコンは高さ 16px を若干超えてしまい、高解像度ディスプレイで PNG 画像（32px × 32px）の場合は元画像より引き延ばされてしまう
=> リンクアイコンの高さ方向の単位を ex → em に変更

astro/src/+util/Ssr.ts, astro/src/layouts/Admin.astro, astro/src/layouts/Kumeta.astro, astro/src/layouts/Madoka.astro, astro/src/layouts/Tokyu.astro, astro/src/layouts/W0s.astro, astro/src/pages/admin/crawler-news/data.astro, astro/src/pages/admin/crawler-news/index.astro, astro/src/pages/admin/crawler-resource/diff.astro, astro/src/pages/admin/crawler-resource/index.astro, astro/src/pages/admin/crawler-resource/log.astro
具体的な影響として、`/tokyu/data` など東急サイトのインデックスページでグローバルナビの現在地表示ができていなかった。
=> `Ssr.getPageUrl()` にてインデックスページの URL が正しく取得できていなかったバグを修正

astro/src/pages/tokyu/data/form_local.astro
- デハ7000とデハ7200が逆になっていたミスを修正
- 7500系の車種記号を修正（出典：[新型車両7500系について 【秩父鉄道からのお知らせ】](https://web.archive.org/web/20100306150007/https://www.chichibu-railway.co.jp/info/2010/03/100302-1.html)）
=> 「譲渡車両編成表」の秩父鉄道ミス修正

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/manga.astro
- 「週刊少年サンデー 1995年43号」（『南国』休載代原）
- 「週刊少年サンデー 2023年39号」（ラムちゃん色紙）
=> 「メディア紹介 — 漫画雑誌」のページにデータ追加

astro/src/pages/kumeta/library/manga.astro
- 登場キャラ名「くまさわくん」が「くまざわくん」になっていた
- 南国20巻のAmazonリンク先が改蔵20巻になっていた
=> 智田うに代原に関する記述ミス修正

astro/style/object/component/_text.css
=> テキストリンクにおいて自分自身のリンクの際はビュレットアイコンを付けない

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/book.astro, astro/src/pages/kumeta/library/manga.astro
- 漫画雑誌に「コミックビーム 2010年10月号」「月刊少年マガジン 2018年3月号」「ハルタ 2021-October Volume 88」を追加
- 図書、一般雑誌に「プレイボーイ 2011年No.48」を追加
- タグの「読み切り」「読切」を後者に統一
- ページ数のミス修正（私立シリウス学園　学校案内）
=> メディア紹介 2023年12月29日更新分

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/manga.astro
- 月刊少年マガジン 2016年9月号の新人賞コメントを追加
- 月刊少年マガジン 2018年3月号の日付ミスを修正
=> メディア紹介 2023年12月29日更新分（追加）

configure/schema/express.json, express/package.json, express/src/app.ts, package-lock.json
従来は対象の祖先ディレクトリしか指定できなかったため、任意の URL を指定できるようにした。
=> Basic 認証の対象 URL を任意に指定できるように変更

astro/src/+util/StructuredData.ts
ISO 8601 では日付のみで問題ないが、Google Search Console では時刻を含めないと「重大ではない問題」として警告される。
[リッチリザルト テスト](https://search.google.com/test/rich-results)での結果は以下のとおり。
- 🆖 `20240101`
- 🆖 `2024-01-01`
- 🆗 `20240101T0000`
- 🆗 `2024-01-01T00:00`
=> JSON-LD の日付に時刻を追加

astro/src/layouts/include/PageHeaderTokyu.astro, astro/src/pages/tokyu/yomoyama/index.astro
- グロナビのページ名表記変更
- ページ数減少に伴い `<h2>` セクション廃止
=> 「東急電車よもやま話」のインデックスページ改修

astro/src/pages/kumeta/index.astro, astro/src/pages/madoka/index.astro, astro/src/pages/madoka/yomoyama/commentary.astro, astro/src/pages/madoka/yomoyama/kumeta.astro, astro/src/pages/madoka/yomoyama/official_news.astro, astro/src/pages/tokyu/data/index.astro, astro/src/pages/tokyu/sty/index.astro, astro/style/object/project/_main-list.css
従来スタイルは `-index` オプションを追加することで対応
=> リンクリストのコンポーネントでフォントサイズを大きくしているのを止める

astro/src/pages/tokyu/an/index.astro
=> インデックスページのリンクリストのフォントサイズが小さくなっていたバグを修正

astro/src/layouts/include/ContentHeader.astro, astro/src/pages/tokyu/machine/cont_fcc.astro, astro/src/pages/tokyu/machine/cont_gto.astro, astro/src/pages/tokyu/machine/cont_high.astro, astro/src/pages/tokyu/machine/cont_igbt.astro, astro/src/pages/tokyu/machine/cont_old.astro
#431 で JSON-LD の最上位階層のページ名を変更した。
しかしページヘッダーのパンくずは一律「ホーム」で問題ない。
=> パンくずの最上位階層のページ名は一律「ホーム」とする

astro/src/components/Image.astro, astro/src/pages/madoka/video/connect.astro, astro/src/pages/madoka/video/shinpen.astro, astro/src/pages/madoka/yomoyama/aj2017_magireco_jiho.astro
SaekiTominaga/media.w0s.jp/pull/50 に対応した修正
Firefox は `<video poster="..." crossorigin="">` で poster 画像が crossorigin 扱いにならないため（Firefox 125, Firefox 127 Nightly）、`poster` 属性は削除する。
=> サムネイル画像の `<img>` 要素に `crossorigin` 属性を付与

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/manga.astro
「週刊少年サンデー 2023年30号」「週刊少年サンデー 2024年27号」を追加
=> メディア紹介 2024年5月29日更新分

astro/style/admin.css, astro/style/error.css, astro/style/foundation/_view-transition.css, astro/style/kumeta.css, astro/style/madoka.css, astro/style/tokyu.css, astro/style/w0s.css
Chrome 126 で[マルチページ アプリケーションのドキュメント間のビュー遷移](https://developer.chrome.com/docs/web-platform/view-transitions/cross-document)が使用可能になる。
=> View transitions を設定

astro/style/object/project/_main-tabular.css
#459 で追加した横スクロールパターンは印刷時の考慮ができていなかったので改修
=> 表の横スクロールは印刷時には無効にする

astro/style/object/project/_main-section.css
2ページ目以降の場合に縦線が上方にずれてしまうバグの対策（Firefox 127, 129 Nightly で確認）
=> 見出し A が Firefox の印刷プレビューで崩れる対策

astro/src/pages/tokyu/machine/cont_old.astro
CS-5 型が設計された時代の東芝の社名は芝浦製作所である。
=> 東京芝浦電気→芝浦製作所に修正

astro/style/foundation/_var.css, astro/style/object/component/_form.css, astro/style/object/component/_text.css, astro/style/object/project/_header.css, astro/style/object/project/_main-library.css
- フォントが環境によって異なるため游明朝を指定
- #528 で配置を `order` にしていたが、見出しが長いときに改行されるのを防ぐため `position: absolute` に戻す
=> 見出しのセルフリンクのスタイルを微調整

astro/src/layouts/Admin.astro, astro/src/layouts/Error.astro, astro/src/layouts/Kumeta.astro, astro/src/layouts/Madoka.astro, astro/src/layouts/Tokyu.astro, astro/src/layouts/W0s.astro, astro/src/layouts/include/ContentBody.astro, astro/src/layouts/include/ContentMain.astro, astro/src/layouts/include/PageHeaderSearch.astro, astro/src/layouts/include/PageHeaderTokyu.astro, astro/src/layouts/include/PageSidebar.astro, astro/src/pages/kumeta/index.astro, astro/src/pages/madoka/index.astro, astro/src/pages/tokyu/index.astro, astro/style/layout/_common.css, astro/style/layout/_error.css, astro/style/layout/_page-full.css, astro/style/object/component/_layout.css, astro/style/object/project/_main-list.css
- ページ内のすべてのコンテンツをランドマーク領域に収める
- `<main>` 領域の変更
- `<aside>` はトップレベルのランドマーク
- 宣伝エリアをコンテンツフッター内からサイドバーの下へ移動
- `<nav>`, `<aside>`, `<search>` は（ページ内に1つであっても）常にラベルを含める
- ランドマークのラベルを見出し要素で提示する（`aria-labelledby` で紐付ける）場合、ID のプレフィックスは `landmark-` とする
=> ランドマーク関連の整備

astro/src/layouts/include/ContentHeader.astro, astro/src/layouts/include/PageHeaderTokyu.astro, astro/style/object/project/_content.css, astro/style/object/project/_header.css
APG タスクフォース曰く、現在カテゴリーは `aria-current=true` を使えとのこと。👉w3c/aria-practices/issues/2583
#491 で現在地を `aria-current=location` に変更したが、[様々な意見、利用ケースを見た](https://fedibird.com/@SaekiTominaga/112942827716630383)結果、`location` がなんなのか分からなくなってきたので `page` に戻す。
`location` が不適切というわけではないが、APG では `page` が採用されているし、自信がないときの安パイという意味での消極的判断。
また `<nav>` 要素でのマークアップを行い、さらにクラス名を `topic-path` から `breadcrumb` へ変更した（これも APG に合わせての変更）。
=> `aria-current` の見直し

astro/src/components/LibNewspaper.astro
現状は新聞タイトルのみから生成しているため、`id="朝日新聞-1"`, `id="朝日新聞-2"` など自動連番のみが付与されるケースが大量に存在してしまい望ましくないため、極力ユニークになるよう日付データなどを追加する。
=> 新聞コンポーネントのセクション ID の生成元データに日付などを追加

astro/src/pages/tokyu/data/history_tokyu.astro, astro/src/pages/tokyu/data/index.astro, astro/src/pages/tokyu/index.astro
基本的には許認可日を基準にしているが、クハ3660形は実態と離れすぎているため、例外的に入籍日（使用開始日）を基準にする。
=> 車歴表におけるクハ3660形の挿入位置を変更

astro/package.json, astro/style/object/project/_main.css, package-lock.json
#569 で緊急的に v12 に戻していたが、解決法が判明したので再び v13 にアップデートする。
`::part()` に付随する疑似クラス、疑似要素はネストせず独立させる必要がある。
=> PostCSS Nesting@13 にアップデート

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/newspaper.astro
=> メディア紹介 2024年10月30日更新分

astro/astro.config.mjs
#603 で Astro v5 にアップデート以後、問い合わせフォームの送信処理ができていなかった（送信ボタンを押すと Astro デフォルトのエラー画面になる）
=> origin ヘッダーのチェックを無効化

express/src/config/express.ts
SaekiTominaga/report.w0s.jp/pull/84
=> CSP でユーザー側起因によるエラー回避の指定を排除（エンドポイント側で対応するため）

astro/src/pages/technology.astro
- blog.w0s.jp, media.w0s.jp, report.w0s.jp の hono 化に伴う記述修正
- ダークモードに関する記述を追加
=> 3ドメインの Express → hono 化に伴う「当サイトの Web 技術」ページ内容追従

express/src/app.ts, express/src/config/express.ts
JSON ファイルで管理していた時代の名残で type プロパティでの判別を行っていたが、from プロパティに直接正規表現を書くことで簡素化する。
=> リダイレクト処理の type プロパティを廃止

astro/src/pages/kumeta/index.astro, astro/src/pages/kumeta/library/book.astro, astro/src/pages/kumeta/library/manga.astro
「ゲッサン 2025年2月号」「アニメージュ 2010年10月号」「アニメージュ 2013年9月号」「アニメージュ 2013年12月号」を追加
=> メディア紹介 2025年2月18日更新分

astro/src/pages/kumeta/index.astro
=> ニュースの自動投稿先を Mastodon に一本化

astro/src/+util/ssr.ts, astro/src/layouts/Admin.astro, astro/src/layouts/Kumeta.astro, astro/src/layouts/Madoka.astro, astro/src/layouts/Tokyu.astro, astro/src/layouts/W0s.astro, astro/src/pages/admin/crawler-news/data.astro, astro/src/pages/admin/crawler-news/index.astro, astro/src/pages/admin/crawler-resource/index.astro
#649 で `build.format` を preserve に変更したことで index 以外のページ URL にも末尾に / が付いてしまい、ローカルナビの現在地表示が無効になってしまった。
=> ページ URL 取得処理を変更

astro/src/components/tokyu/+phrasing/MachineFormAPS.astro, astro/src/components/tokyu/+phrasing/MachineFormCont.astro, astro/src/pages/tokyu/data/form_car.astro, astro/src/pages/tokyu/data/form_line.astro
MOS-FET のように用語そのものにハイフンが含まれるケースに対応できないため
=> GTO-VVVF のようなハイフン区切りをやめてスペース区切りにする

astro/src/layouts/head/Kumeta.astro, astro/src/layouts/head/Madoka.astro, astro/src/layouts/head/Site.astro, astro/src/layouts/head/Tokyu.astro
Chrome 139 は `sizes` 属性がないと PNG への無駄なリクエストが発生するため。👉[Safari にも実装が入ることだし、あらためて SVG ファビコンのベスト・プラクティスを考えよう 2025 晩夏（実験） / JeffreyFrancesco.org](https://jeffreyfrancesco.org/weblog/2025082901/)
=> Favicon の `link` 要素に `sizes` 属性を追加

astro/src/+dao/CrawlerNewsDao.ts, astro/src/+dao/CrawlerResourceDao.ts, astro/src/pages/admin/crawler-news/index.astro, astro/src/pages/admin/crawler-resource/index.astro
従来は http:// → https:// などの URL 変更時も既存データを削除→新規追加しなければならなかったが、直接 update を掛けられるようにした。
=> ウェブ巡回で URL を更新できるように

astro/src/+dao/CrawlerDao.ts, astro/src/+dao/CrawlerNewsDao.ts, astro/src/+dao/CrawlerResourceDao.ts
- `m_class` テーブル → `m_category`
- `d_news` テーブルの `class` カラム → `category`
=> `crawler.db` のテーブル名、カラム名変更に対応
